[defaults]
fastq_input = "fastq_chunked/*.fastq.gz"
basecall = false
pod5_chunk = false
pod5_split = false
gfa_grouping = "/home/jqs1/scratch/sequencing/sequencing_references/barcode.gfa"
gfa_variants = "/home/jqs1/scratch/sequencing/sequencing_references/pLIB502-503.gfa"
consensus_args = "--method abpoa --no-phred-output --max-length 10000 --max-divergence 0.3"
consensus_jobs = 400
consensus_jobs_per_align_job = 8
find_duplex_pairs_args = "-x UNS9,BC:T7_prom,BC:UMI:upstream,BC:UMI,BC:UMI:downstream,BC:spacer2,BC:term:T7,BC:term:T7hyb10,JUNC10_UNS10"
prepare_reads_args = "-x UNS9,BC:T7_prom,BC:UMI:upstream,BC:UMI,BC:UMI:downstream,BC:spacer2,BC:term:T7,BC:term:T7hyb10,JUNC10_UNS10"
